### ISSUE TITLE
Projects Deleted on Selection of Other Projects

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#139]
## Problem
After creating a project, the project is deleted immediately upon selecting any other project.

### Steps to reproduce
Create a project
Select any other project that currently exists
The newly created project is deleted.

### Environment
Chrome

### Expected behavior
Project should exist in the drop down menu, and does initially on creation

### Observed behavior
Project is automatically deleted and removed upon creation

*Subheadings below are optional; remove if not applicable.*
### Console output/errors
chunk-6BKLQ22S.js?v=88f7fd1e:521 Warning: useMemo received a final argument that is not an array (instead, received `string`). When specified, the final argument must be an array.
    at TaskPage (http://moxie.cs.oswego.edu:49000/src/pages/TaskPage.jsx:30:28)
    at ProjectPage (http://moxie.cs.oswego.edu:49000/src/pages/ProjectPage.jsx:22:23)
    at RenderedRoute (http://moxie.cs.oswego.edu:49000/node_modules/.vite/deps/react-router-dom.js?v=b6952a95:4092:5)
    at Outlet (http://moxie.cs.oswego.edu:49000/node_modules/.vite/deps/react-router-dom.js?v=b6952a95:4467:26)
    at Provider (http://moxie.cs.oswego.edu:49000/node_modules/.vite/deps/chunk-MH7BDFHM.js?v=88f7fd1e:62:15)
    at Dialog (http://moxie.cs.oswego.edu:49000/node_modules/.vite/deps/chunk-MH7BDFHM.js?v=88f7fd1e:1437:5)
    at Root2 (http://moxie.cs.oswego.edu:49000/node_modules/.vite/deps/vaul.js?v=d6faa343:787:24)
    at Drawer (http://moxie.cs.oswego.edu:49000/components/ui/drawer.jsx:21:3)
    at main
    at div
    at PageLayout
    at ProjectProvider (http://moxie.cs.oswego.edu:49000/components/ProjectProvider.jsx:21:43)
    at RenderedRoute (http://moxie.cs.oswego.edu:49000/node_modules/.vite/deps/react-router-dom.js?v=b6952a95:4092:5)
    at Routes (http://moxie.cs.oswego.edu:49000/node_modules/.vite/deps/react-router-dom.js?v=b6952a95:4531:5)
    at Router (http://moxie.cs.oswego.edu:49000/node_modules/.vite/deps/react-router-dom.js?v=b6952a95:4474:15)
    at BrowserRouter (http://moxie.cs.oswego.edu:49000/node_modules/.vite/deps/react-router-dom.js?v=b6952a95:5219:5)
    at Component

### Screenshot
*Shows the incorrect behavior.*
![image](https://github.com/user-attachments/assets/c054344d-ac40-4e45-9025-fef096ea4a3c)

https://github.com/user-attachments/assets/868b290d-641b-483d-b0ac-5e3458195944

**Comment by PiesArentSquare** [comment]
should be fixed in e09a092ef6e92bd429ce94e2194af4031c016318
